spring:
  application:
    name : boot-netty-server
netty:
    port: 9000
    #Boss ??
    # ??????????????????????????????????Boss ?????????????????Worker ?????????????
    boss-thread-count: 1
    #worker????? ??????????? IO ????????????????????Boss ?????????? Worker ?????????
    worker-thread-count: 10
    host: 127.0.0.1
server:
  port: 8081