spring:
  application:
    name: boot-netty-client

netty:
    port: 9000
    host: 127.0.0.1
    #Boss ??
    # ??????????????????????????????????Boss ?????????????????Worker ?????????????
    boss-thread-count: 1
    #worker????? ??????????? IO ????????????????????Boss ?????????? Worker ?????????
    worker-thread-count: 10
server:
  port:   8080
