spring:
  banner:
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

server:
  enabled: true
  bind_address: 0.0.0.0
  bind_port: 9876
  netty:
    #??????????
    leak_detector_level: DISABLED
    boss_group_thread_count: 1
    worker_group_thread_count: 12
    #??????
    max_payload_size: 65536
